### PR TITLE
READme.md

### PR DESCRIPTION
**Pull request by nocryptoinjectorspls**
POS

### CODE REVIEW

**Comment by master131** [comment]
@nocryptoinjectorspls Did you even download it from a legitimate source? I hope you realise that anyone can attach their own malicious programs to any legitimate application.

There are official mirrors on the README page. It's not my fault that you downloaded it from an unofficial mirror.

**Comment by master131** [comment]
Unless your EXE matches this SHA-256 for version 3.7.3, then it's not an official version and most likely you've downloaded a modified/infected version:
b65f40618f584303ca0bcf9b5f88c233cc4237699c0c4bf40ba8facbe8195a46

**Comment by nocryptoinjectorspls** [comment]
yeah the malicious actor is you. the >bats show it came from the program on top of that here is the HASH( 6d04bd042d09bef9de22f97275ee57db8cfe09818ab58897aa9197d4c6d3f68b ) It has the .NET libs aswell. even windows defender caught your crypto injector.

**Comment by master131** [comment]
@nocryptoinjectorspls Check again mate; the Github and MPGH mirrors on the official README do not have that program that you mention at all.

**Pull request closed without merging**
